areas:  
  - area:
      coords: 
        - x: -139.85
          y: 62.58
        - x: -126.91
          y: -47.81
        - x: -66.26
          y: -80.52
        - x: 42.77
          y: -92.11
        - x: 100.0
          y: -50.0
        - x: 140.89
          y: 10.79
        - x: 129.31
          y: 100.74
        - x: 61.85
          y: 172.97
        - x: -83.98
          y: 194.09


